local L = {
	SETTING_SPLIT_MARKER_LABEL = "分割标记",
	SETTING_SPLIT_MARKER_HINT = "指示消息被分割的位置",

	SETTING_SHOW_MESSAGE_INDEX_LABEL = "显示消息索引",
	SETTING_SHOW_MESSAGE_INDEX_HINT = "在每条消息前添加索引",

	SETTING_HANDLE_RP_SYNTAX_LABEL = "启用RP格式",
	SETTING_HANDLE_RP_SYNTAX_HINT = "在消息之间保留RP格式和颜色",

	SETTING_HANDLE_NPC_SPEECH_LABEL = "启用NPC前缀",
	SETTING_HANDLE_NPC_SPEECH_HINT = "以NPC身份发言时为消息添加NPC标记",

	SETTING_HANDLE_CAPITALIZATION_LABEL = "自动大写",
	SETTING_HANDLE_CAPITALIZATION_HINT = "必要时将第一条消息首字母大写",

	SETTING_HANDLE_PUNCTUATION_LABEL = "自动标点",
	SETTING_HANDLE_PUNCTUATION_HINT = "如果最后一条消息没有结尾标点，则添加句号",

	SETTING_ENABLE_UNDO_LABEL = "启用Ctrl+Z撤销",
	SETTING_ENABLE_UNDO_HINT = "按Ctrl+Z恢复已删除或已关闭的消息",

	NOTIF_HW_PROMPT = "按 [Enter] 继续",
	NOTIF_MSG_THROTTLED = "消息已限流",
	NOTIF_WAITING_FOR_THROTTLE = "等待中...",
};

------------

Chattery.Strings:Register(L);
