local L = {
	SETTING_SPLIT_MARKER_LABEL = "分割標記",
	SETTING_SPLIT_MARKER_HINT = "指示訊息被分割的位置",

	SETTING_SHOW_MESSAGE_INDEX_LABEL = "顯示訊息索引",
	SETTING_SHOW_MESSAGE_INDEX_HINT = "在每條訊息前加入索引",

	SETTING_HANDLE_RP_SYNTAX_LABEL = "啟用RP格式",
	SETTING_HANDLE_RP_SYNTAX_HINT = "在訊息之間保留RP格式與顏色",

	SETTING_HANDLE_NPC_SPEECH_LABEL = "啟用NPC前綴",
	SETTING_HANDLE_NPC_SPEECH_HINT = "以NPC身份發言時為訊息加入NPC標記",

	SETTING_HANDLE_CAPITALIZATION_LABEL = "自動大寫",
	SETTING_HANDLE_CAPITALIZATION_HINT = "必要時將第一條訊息首字母大寫",

	SETTING_HANDLE_PUNCTUATION_LABEL = "自動標點",
	SETTING_HANDLE_PUNCTUATION_HINT = "如果最後一條訊息沒有結尾標點，則加入句號",

	SETTING_ENABLE_UNDO_LABEL = "啟用Ctrl+Z復原",
	SETTING_ENABLE_UNDO_HINT = "按Ctrl+Z還原已刪除或已關閉的訊息",

	NOTIF_HW_PROMPT = "按 [Enter] 繼續",
	NOTIF_MSG_THROTTLED = "訊息已限流",
	NOTIF_WAITING_FOR_THROTTLE = "等待中...",
};

------------

Chattery.Strings:Register(L);
